language: cpp
jobs:
  include:
    - name: "macOS Build"
      os: osx
      osx_image: xcode12.2
      script: mkdir build && cd build && cmake -G Xcode .. && cmake --build .
    - name: "Windows Build"
      os: windows
      script: mkdir build && cd build && cmake -G "Visual Studio 15 2017" .. && cmake --build .
    - name: "Linux Build"
      dist: focal
      script: mkdir build && cd build && cmake .. && cmake --build .
